version: '3.8'

services:
  ai_assistent:
    build:
      context: .
      dockerfile: ai_assistant/Dockerfile
    ports:
      - "8000:8000"
  ai_planner:
    build:
      context: .
      dockerfile: ai_planner/Dockerfile
    ports:
      - "8001:8001"
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin