version: '3.8'

services:
  ai_assistent:
    build:
      context: .
      dockerfile: ai_assistant/Dockerfile
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
  ai_planner:
    build:
      context: .
      dockerfile: ai_planner/Dockerfile
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1
  ai_optimizer:
    build:
      context: .
      dockerfile: ai_optimizer/Dockerfile
    ports:
      - "8002:8002"